import {it,expect} from 'vitest';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {loadSimple,saveSimple} from '../src/main/simple-store';import {simpleDefaults} from '../src/shared/simple';import {DailyRecords,localDate} from '../src/main/daily-records';
const temp=(run:(dir:string)=>void)=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'interlude-records-'));try{run(dir)}finally{fs.rmSync(dir,{recursive:true})}};
it('schema 2 preferences migrate without losing position, theme, login, or custom durations',()=>temp(dir=>{fs.writeFileSync(path.join(dir,'simple-settings.json'),JSON.stringify({schemaVersion:2,workMinutes:40,restMinutes:4,theme:'dark',placement:'corner',openAtLogin:true}));const loaded=loadSimple(dir);expect(loaded.warning).toBe('');expect(loaded.settings).toEqual({...simpleDefaults,workMinutes:40,restMinutes:4,theme:'dark',placement:'corner',openAtLogin:true});saveSimple(dir,loaded.settings);expect(loadSimple(dir).settings).toEqual(loaded.settings)}));
it('legacy preferences migrate while historical data stays untouched; corrupt files are backed up',()=>temp(dir=>{fs.writeFileSync(path.join(dir,'settings.json'),JSON.stringify({tracking:{shortWorkSec:1200,shortBreakSec:240},theme:'dark',startup:{openAtLogin:true}}));fs.writeFileSync(path.join(dir,'events-old.jsonl'),'kept');expect(loadSimple(dir).settings).toMatchObject({workMinutes:20,restMinutes:4,theme:'dark',openAtLogin:true});fs.writeFileSync(path.join(dir,'simple-settings.json'),'broken');expect(loadSimple(dir).warning).not.toBe('');expect(fs.readdirSync(dir).some(n=>n.includes('.backup-'))).toBe(true);expect(fs.readFileSync(path.join(dir,'events-old.jsonl'),'utf8')).toBe('kept')}));
it('daily records keep just the three estimated measures and survive restart',()=>temp(dir=>{const r=new DailyRecords(dir),wall=new Date(2026,8,6,9).getTime();for(let i=1;i<=120;i++)r.use(1000,wall+i*1000);r.rest(wall+120000);r.use(1000,wall+121000);r.flush();const saved=new DailyRecords(dir);expect(saved.days).toEqual([{date:localDate(wall),rises:1,longestSitMs:120000,totalSitMs:121000}]);expect(saved.summary(wall)).toMatchObject({averageRises:1,longestSitMinutes:2,days:1});expect(Object.keys(JSON.parse(fs.readFileSync(path.join(dir,'daily-records.json'),'utf8')).days[0]).sort()).toEqual(['date','longestSitMs','rises','totalSitMs'])}));
it('an interval spanning local midnight is divided between dates and histories remain local',()=>temp(dir=>{const r=new DailyRecords(dir),wall=new Date(2026,8,7).getTime();r.use(2000,wall+1000);r.flush();expect(r.days.map(d=>[d.date,d.totalSitMs,d.longestSitMs])).toEqual([['2026-09-06',1000,1000],['2026-09-07',1000,1000]]);expect(fs.readdirSync(dir)).toEqual(['daily-records.json'])}));
it('a rolling week keeps the days either side of a Monday and drops anything older',()=>temp(dir=>{const r=new DailyRecords(dir),stale=new Date(2026,8,1,12).getTime(),sunday=new Date(2026,8,6,12).getTime(),monday=new Date(2026,8,7,12).getTime(),tuesday=new Date(2026,8,8,12).getTime();r.use(1000,stale);r.rest(stale);r.use(1000,sunday);r.rest(sunday);r.use(1000,monday);r.rest(monday);expect(r.summary(tuesday).days).toBe(2);expect(r.summary(tuesday).averageRises).toBe(1)}));
it('bad history is retained in a backup, rather than silently overwritten',()=>temp(dir=>{fs.writeFileSync(path.join(dir,'daily-records.json'),'bad');const r=new DailyRecords(dir);expect(r.warning).not.toBe('');expect(fs.readdirSync(dir).some(n=>n.includes('.backup-'))).toBe(true)}));

it.each([true,false])('schema 3 retires sound=%s while retaining every other preference',soundEnabled=>temp(dir=>{
 const old={schemaVersion:3,workMinutes:40,restMinutes:4,theme:'dark',placement:'corner',openAtLogin:true,soundEnabled};
 fs.writeFileSync(path.join(dir,'simple-settings.json'),JSON.stringify(old));const loaded=loadSimple(dir);
 expect(loaded.warning).toBe('');expect(loaded.settings).toEqual({schemaVersion:4,workMinutes:40,restMinutes:4,theme:'dark',placement:'corner',openAtLogin:true});
 saveSimple(dir,loaded.settings);expect(JSON.parse(fs.readFileSync(path.join(dir,'simple-settings.json'),'utf8'))).not.toHaveProperty('soundEnabled');expect(loadSimple(dir).settings).toEqual(loaded.settings);
}));
