import {_electron as electron,expect} from '@playwright/test';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
const version=JSON.parse(fs.readFileSync('package.json')).version,dev=!process.env.INTERLUDE_QA_EXECUTABLE&&process.env.INTERLUDE_DEV!=='0',smoke=process.env.INTERLUDE_QA_SMOKE==='1';
const out=process.env.INTERLUDE_QA_OUT??'reports/current',dir=fs.mkdtempSync(path.join(os.tmpdir(),'interlude-panel-'));fs.mkdirSync(out,{recursive:true});
fs.writeFileSync(path.join(dir,'onboarded'),'1');fs.writeFileSync(path.join(dir,'simple-settings.json'),JSON.stringify({schemaVersion:3,workMinutes:30,restMinutes:1,openAtLogin:false,soundEnabled:true,theme:'light',placement:'top'}));
const legacyPosition=JSON.stringify({schemaVersion:1,displayId:null,x:.24,y:.67,hidden:false});fs.writeFileSync(path.join(dir,'companion-position.json'),legacyPosition);
const executable=process.env.INTERLUDE_QA_EXECUTABLE??(dev?path.resolve('node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'):path.join(os.homedir(),'Applications/Interlude.app/Contents/MacOS/Interlude'));
const report={version,development:dev,smoke,checks:[],fixture:'Isolated user data and deterministic native-presence signals; actual Electron windows. Full mode uses a real 60-second rest and real 8-/12-second hide deadlines.'};
let app;const errors=[];
const main=code=>app.evaluate(({app},code)=>{const m=process.getBuiltinModule('module').createRequire(app.getAppPath()+'/dist/main.cjs')(app.getAppPath()+'/dist/main.cjs');return Function('m','c',code)(m,m.cycle)},code);
const menu=label=>app.evaluate(({Menu},label)=>Menu.getApplicationMenu().items[0].submenu.items.find(i=>i.label===label).click(),label);
const native=()=>app.evaluate(({BrowserWindow,screen})=>BrowserWindow.getAllWindows().map(w=>({id:w.id,view:(w.webContents.getURL()?new URL(w.webContents.getURL()).searchParams.get('view'):'loading'),visible:w.isVisible(),bounds:w.getBounds(),workArea:screen.getDisplayMatching(w.getBounds()).workArea,display:screen.getDisplayMatching(w.getBounds()).bounds})));
const state=()=>main('return c.snapshot()');
async function page(kind){let p;await expect.poll(()=>{p=app.windows().find(w=>w.url().includes(`view=${kind}`));return !!p}).toBe(true);await p.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));return p}
async function shown(kind,height){await expect.poll(async()=>{const w=(await native()).filter(w=>w.visible);return w.length===1&&w[0].view===kind&&w[0].bounds.height===height},{timeout:5000}).toBe(true);const w=(await native()).find(w=>w.visible);expect(w.bounds.width).toBe(320);expect((await native()).some(w=>w.view==='widget')).toBe(false);return w}
async function capture(p,name){await p.waitForTimeout(450);await app.evaluate(async({BrowserWindow},{url,file})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL()===url);process.getBuiltinModule('fs').writeFileSync(file,(await w.webContents.capturePage()).toPNG())},{url:p.url(),file:path.resolve(out,`${name}.png`)});}
async function due(){await main("c.reset();c.paused=false;c.blocked.clear();c.grace=0;c.stage=4;c.usageMs=1800000;c.remaining=0;c.phase='due';c.clock.activity=()=>({idleSeconds:0,state:'active',screenAwake:true});c.last=c.clock.mono()");await expect.poll(async()=>(await state()).announced??(await native()).some(w=>w.view==='card'&&w.visible),{timeout:5000}).toBe(true);return page('card')}
try{
 app=await electron.launch({executablePath:executable,args:dev?['.','--background']:['--background'],env:{...process.env,INTERLUDE_DATA_DIR:dir}});app.on('window',p=>p.on('pageerror',e=>errors.push(String(e))));
 report.actualVersion=await app.evaluate(({app})=>app.getVersion());expect(report.actualVersion).toBe(version);
 await expect.poll(()=>main('return !!c')).toBe(true);expect((await state()).settings).not.toHaveProperty('soundEnabled');await main("m.environment.stop();m.environment.value={captureActive:false,fullscreenQuiet:false,reducedMotion:false,screenAwake:true,mediaActive:false,appSwitch:false};c.blocked.clear();c.clock.activity=()=>({idleSeconds:0,state:'active',screenAwake:true})");
 await new Promise(r=>setTimeout(r,1200));expect(await native()).toEqual([]);report.checks.push('Onboarded background launch has no BrowserWindow, renderer surface or desktop widget.');
 const labels=await app.evaluate(({Menu})=>Menu.getApplicationMenu().items[0].submenu.items.map(i=>i.label));expect(labels).toEqual(['打开小窗','设置','退出间歇…']);
 await menu('打开小窗');let panel=await page('tray');await app.evaluate(({app,BrowserWindow})=>{app.focus({steal:true});BrowserWindow.getAllWindows().find(w=>w.isVisible()).focus()});
 await expect(panel.locator('.quiet-panel')).toBeVisible();const first=await shown('tray',320);expect(first.bounds.y).toBe(first.workArea.y+8);await capture(panel,'panel-light');
 const api=await panel.evaluate(()=>Object.keys(window.interlude));expect(api.some(k=>/widget|source/i.test(k))).toBe(false);expect(await panel.locator('.desktop-companion,.widget-bird').count()).toBe(0);await expect(panel.locator('canvas.graphite-bird')).toHaveAttribute('data-art','ready');await expect(panel.locator('canvas.graphite-bird')).toHaveAttribute('data-clip','idle');
 await panel.getByRole('button',{name:'暂停提醒',exact:true}).click();await expect(panel.locator('canvas.graphite-bird')).toHaveAttribute('data-frame','0');await panel.getByRole('button',{name:'继续提醒',exact:true}).click();await expect.poll(()=>panel.locator('canvas.graphite-bird').getAttribute('data-frame')).not.toBe('0');
 await main("c.remaining=18*60000;c.reminderWindowMs=45*60000;c.usageMs=27*60000;c.last=c.clock.mono();c.notify()");await panel.emulateMedia({reducedMotion:'reduce'});await expect(panel.locator('.editorial-number')).toHaveText('18');await expect(panel.locator('canvas.graphite-bird')).toHaveAttribute('data-frame','0');await expect(panel.locator('.hand-drawn-number')).toHaveAttribute('data-glyphs','18');await expect(panel.locator('.hand-drawn-number')).toBeVisible();await capture(panel,'reference-light');await panel.emulateMedia({reducedMotion:'no-preference'});await main('c.reset();c.notify()');
 await menu('设置');await expect(panel.locator('.preferences-page')).toBeVisible();expect((await shown('tray',396)).id).toBe(first.id);
 await panel.getByRole('radio',{name:'45 分钟',exact:true}).check();await panel.getByRole('button',{name:'返回',exact:true}).click();await expect(panel.getByRole('dialog')).toBeVisible();await panel.getByRole('button',{name:'继续编辑',exact:true}).click();
 await panel.getByRole('radio',{name:'30 分钟',exact:true}).check();await panel.getByRole('radio',{name:'屏幕角落',exact:true}).check();await expect(panel.getByRole('switch')).toHaveCount(1);await expect(panel.getByText('声音',{exact:true})).toHaveCount(0);await capture(panel,'settings-light');
 await panel.getByRole('radio',{name:'深色',exact:true}).check();
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.isVisible()).webContents.setZoomFactor(640/420));await panel.waitForTimeout(200);
 const layout=await panel.getByRole('button',{name:'保存设置',exact:true}).evaluate(e=>({bottom:e.getBoundingClientRect().bottom,height:innerHeight,width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));expect(layout.bottom).toBeLessThanOrEqual(layout.height);expect(layout.scrollWidth).toBeLessThanOrEqual(layout.width);await capture(panel,'settings-200');
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.isVisible()).webContents.setZoomFactor(320/420));await panel.getByRole('button',{name:'保存设置',exact:true}).click();
 const corner=await shown('tray',320);expect(corner.id).toBe(first.id);expect(corner.bounds.x+320).toBe(corner.workArea.x+corner.workArea.width-16);expect(corner.bounds.y+320).toBe(corner.workArea.y+corner.workArea.height-16);await capture(panel,'panel-dark');await menu('设置');await expect(panel.locator('.preferences-page')).toBeVisible();await shown('tray',396);await capture(panel,'settings-dark');await panel.getByRole('button',{name:'返回',exact:true}).click();await shown('tray',320);
 report.checks.push('The retained small window opens from the menu, expands in place for Settings, protects drafts, supports 200% settings zoom and saves day/night plus corner placement. Widget menus and preload APIs are absent.');
 await panel.evaluate(()=>window.__bird=document.querySelector('.paper-bird'));
 const birdBox=await panel.locator('.editorial-bird').boundingBox();
 await panel.getByRole('button',{name:'现在休息',exact:true}).click();await expect(panel.getByLabel('休息剩余时间')).toBeVisible();expect((await shown('tray',320)).id).toBe(first.id);expect(await panel.evaluate(()=>window.__bird===document.querySelector('.paper-bird'))).toBe(true);expect(await panel.locator('.editorial-bird').boundingBox()).toEqual(birdBox);await capture(panel,'rest-dark');
 await panel.getByLabel('召回小歇，提前结束休息').click();await expect(panel.locator('.returned')).toBeVisible();await expect(panel.locator('.paper-bird')).toHaveAttribute('data-pose','perched');expect(await panel.locator('.editorial-bird').boundingBox()).toEqual(birdBox);await capture(panel,'return-early-dark');
 expect((await state()).restCompletion.credited).toBe(false);report.checks.push('Starting and recalling a rest retain the same native window and bird DOM; unqualified early recall preserves usage and shows return feedback.');
 if(smoke){
  await panel.getByRole('button',{name:'继续做事',exact:true}).click();let reminder=await due();await shown('card',320);await capture(reminder,'reminder-dark');await reminder.getByRole('button',{name:'现在休息',exact:true}).click();await expect(reminder.getByLabel('休息剩余时间')).toBeVisible();await reminder.getByLabel('召回小歇，提前结束休息').click();await expect(reminder.locator('.returned')).toBeVisible();
  report.checks.push('Legacy sound-enabled settings migrate without an audio field; Settings contains only the login switch. Manual start, due reminder and return remain available.');
 }
 if(!smoke){
  await panel.getByRole('button',{name:'继续做事',exact:true}).click();await expect.poll(async()=>(await native()).length,{timeout:6500}).toBe(0);
  let card=await due();await shown('card',320);await capture(card,'reminder-dark');const firstRemaining=(await state()).usageMs;
  await card.getByRole('button',{name:'收起提醒',exact:true}).click();expect((await state()).deferred).toBe('snoozed');expect((await state()).usageMs).toBeGreaterThanOrEqual(firstRemaining);
  card=await due();const reminderShown=performance.now();await expect.poll(async()=>(await state()).deferred,{timeout:14500}).toBe('snoozed');report.reminderTimeoutMilliseconds=performance.now()-reminderShown;expect(report.reminderTimeoutMilliseconds).toBeGreaterThan(11000);expect((await native()).filter(w=>w.visible)).toEqual([]);
  report.checks.push('A due reminder automatically opens the small card. Close and the real 12-second deadline both snooze without losing accumulated use.');
  card=await due();await card.getByRole('button',{name:'现在休息',exact:true}).click();await expect(card.getByLabel('休息剩余时间')).toBeVisible();await shown('card',320);const restWindowId=(await native()).find(w=>w.visible).id;
  await main("c.clock.activity=()=>({idleSeconds:Math.max(0,(c.clock.mono()-c.restStarted)/1000),state:'active',screenAwake:true})");
  const started=await main('return c.restStarted'),deadline=await main('return c.restEnd');await capture(card,'rest-full-minute-dark');
  await expect.poll(async()=>(await native()).filter(w=>w.visible).length,{timeout:9500}).toBe(0);await expect.poll(async()=>(await native()).length,{timeout:6500}).toBe(0);
  expect(await main('return c.restEnd')).toBe(deadline);report.checks.push('Rest card really hides after eight seconds and its renderer is released after five more; the rest deadline continues without any window.');
  await expect.poll(async()=>(await state()).phase,{timeout:65000,intervals:[500]}).toBe('working');card=await page('card');await expect(card.locator('.returned')).toBeVisible();await shown('card',320);expect((await native()).find(w=>w.visible).id).not.toBe(restWindowId);expect((await state()).restCompletion.credited).toBe(true);
  report.restElapsedMilliseconds=await main(`return c.clock.mono()-${started}`);expect(report.restElapsedMilliseconds).toBeGreaterThanOrEqual(60000);await expect(card.locator('.paper-bird')).toHaveAttribute('data-pose','perched');await capture(card,'return-complete-dark');await card.getByRole('button',{name:'继续做事',exact:true}).click();
  report.checks.push('A full real-time 60-second valid rest completes while no window exists, then recreates the return card and lands the bird; the new round is credited.');
  await main("m.environment.value.captureActive=true;c.reset();c.stage=4;c.remaining=0;c.phase='due';c.last=c.clock.mono()");await new Promise(r=>setTimeout(r,1500));expect((await native()).filter(w=>w.visible)).toEqual([]);
  await main('m.environment.value.captureActive=false');card=await page('card');await expect(card.getByRole('button',{name:'现在休息',exact:true})).toBeVisible();await shown('card',320);await card.getByRole('button',{name:'收起提醒',exact:true}).click();
  await main("m.environment.value.fullscreenQuiet=true;c.reset();c.stage=4;c.remaining=0;c.phase='due';c.last=c.clock.mono()");await new Promise(r=>setTimeout(r,1500));expect((await native()).filter(w=>w.visible)).toEqual([]);await main('m.environment.value.fullscreenQuiet=false');await expect.poll(async()=>(await native()).some(w=>w.view==='card'&&w.visible)).toBe(true);card=await page('card');await card.getByRole('button',{name:'收起提醒',exact:true}).click();
  report.checks.push('Injected active-capture and fullscreen-quiet signals defer automatic cards; the due card appears after each signal clears. No system recording is claimed by this fixture.');
  await expect.poll(async()=>(await native()).length,{timeout:6500}).toBe(0);
  await app.close();app=await electron.launch({executablePath:executable,args:dev?['.','--background']:['--background'],env:{...process.env,INTERLUDE_DATA_DIR:dir}});await expect.poll(()=>main('return !!c')).toBe(true);await new Promise(r=>setTimeout(r,1200));expect(await native()).toEqual([]);await menu('打开小窗');panel=await page('tray');await shown('tray',320);expect((await state()).settings.theme).toBe('dark');expect((await state()).settings.placement).toBe('corner');
  expect(fs.readFileSync(path.join(dir,'companion-position.json'),'utf8')).toBe(legacyPosition);report.checks.push('Restart is windowless, the menu reopens the small window with saved preferences, and the retired widget-position file is untouched.');
  await app.close();fs.unlinkSync(path.join(dir,'onboarded'));app=await electron.launch({executablePath:executable,args:dev?['.','--background']:['--background'],env:{...process.env,INTERLUDE_DATA_DIR:dir}});panel=await page('tray');await expect(panel.getByRole('button',{name:'开启提醒',exact:true})).toBeVisible();await shown('tray',320);await capture(panel,'welcome-dark');
  await menu('设置');await expect(panel.locator('.preferences-page')).toBeVisible();await panel.getByRole('button',{name:'保存设置',exact:true}).click();await expect(panel.getByRole('button',{name:'开启提醒',exact:true})).toBeVisible();expect((await state()).active).toBe(false);await panel.getByRole('button',{name:'开启提醒',exact:true}).click();await expect(panel.getByRole('button',{name:'现在休息',exact:true})).toBeVisible();expect((await state()).active).toBe(true);report.checks.push('Fresh background launch opens the welcome window; saving optional Settings does not activate reminders until the user selects Enable.');
 }
 expect(errors).toEqual([]);report.status='PASS';console.log(JSON.stringify(report,null,2));
}catch(error){report.status='FAIL';report.error=String(error);try{report.windows=await native();report.state=await state()}catch{}throw error}
finally{report.errors=errors;fs.writeFileSync(`${out}/panel-qa.json`,JSON.stringify(report,null,2));await app?.close().catch(()=>{});if(report.status==='PASS')fs.rmSync(dir,{recursive:true,force:true});}
