name: Native desktop packages
on: [workflow_dispatch]
permissions:
  contents: read
jobs:
  build:
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macos-14, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '24'
          cache: npm
      - run: npm ci
      - run: npm run typecheck
      - run: npm test
      - run: npm run make
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: interlude-${{ matrix.os }}
          path: out/**/make/
          if-no-files-found: error
          retention-days: 14
